theme: jekyll-theme-cayman
title: HES Developer
description: Presentacion de trabajos realazados utilizando diferentes tecnologias y lenguajes de programacion. C#, PHP, JavaScript, HTML, CSS, JQuery, MS SQL, MySQL
favicon: ![Image](imgs/login.jpg)
